// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUfjszc7dVZeMIQBMetl7Ywan7cdCX1Y',
    appId: '1:901228709580:web:276c54b86e6b851ce56469',
    messagingSenderId: '901228709580',
    projectId: 'shopping-app-1e6f6',
    authDomain: 'shopping-app-1e6f6.firebaseapp.com',
    storageBucket: 'shopping-app-1e6f6.firebasestorage.app',
    measurementId: 'G-JG333193M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4VES1fMMmc52yLcPSgmfXkyBVRlGPG7k',
    appId: '1:901228709580:android:a6192c603f90f301e56469',
    messagingSenderId: '901228709580',
    projectId: 'shopping-app-1e6f6',
    storageBucket: 'shopping-app-1e6f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjX7ZfvxSbgSppQEgddKKIhcDTIghJl0',
    appId: '1:901228709580:ios:b932fd86a88a1c78e56469',
    messagingSenderId: '901228709580',
    projectId: 'shopping-app-1e6f6',
    storageBucket: 'shopping-app-1e6f6.firebasestorage.app',
    androidClientId: '901228709580-vr5ncadfu5rpdj32oqcmtfjs9rm3rep9.apps.googleusercontent.com',
    iosClientId: '901228709580-rm84dh97ih30smu5i896bu3o5sepgtrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
